# Generated by Django 6.0.2 on 2026-02-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='privacy_consent',
            field=models.BooleanField(default=False, help_text='Datenschutzerklärung akzeptiert'),
        ),
    ]
